### PR TITLE
Configuration and build script for CentOS 7 on AWS

### PR DESCRIPTION
**Pull request by giancarlopetrini**
## Description

Scripts are proposed to be located in reentry-resources-hub/deployment and will be accessed via git clone on target machine. The URL in the readme that references git clone will need to be updated if/when PR is merged. The scripts primary roles are to: disable selinux, allow inbound http(s) traffic, install epel release, node v8.x, various dependencies, restart server when necessary, replace nginx configuration file with reverse proxy config, and run the needed yarn commands.

## Related Issue

https://github.com/CodeForNC/reentry-resources-hub/issues/45

## Motivation and Context

Looking to automate the deployment in AWS environments as quickly as possible. It's a simple an succinct script that should be easily modified in the future, as needed.

## How Has This Been Tested?

Script was executed numerous line by line during initial writing using a newly installed CentOS 7 minimal image. Additionally, scripts were run in totality on same CentOS 7 machine after clearing all previous package installations and repos. In all tests, browsing was possible to http://Ip_Addr:80 of the host server, which successfully proxied to port 3001 (can add 3000 as additional location in nginx config if needed).

## Checklist:

- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Comment by giancarlopetrini** [comment]
@ejaxon here you go!

**Comment by ejaxon** [comment]
@giancarlopetrini - Perfect, thanks! I'll pull down and modify the repo URLs now, but this is very helpful.

**Comment by ejaxon** [comment]
May want to ask some questions later about specific pieces (just for better understanding).

**Comment by giancarlopetrini** [comment]
please do, you can shoot me something in Slack if you want

**Comment by marshallj** [comment]
@ejaxon & @giancarlopetrini, loop me in here too. I've not used Jenkins before either, and would love to get a better understanding as well.

**Pull request merged**
