### PR TITLE
Created Deployment Scripts and Instructions for usage with CentOS 7 and AWS

### PR DESCRIPTION
**Pull request by giancarlopetrini**
## Description

Scripts are proposed to be located in reentry-resources-hub/deployment and will be accessed via git clone on target machine. The URL in the readme that references git clone will need to be updated if/when PR is merged. The scripts primary roles are to: disable selinux, allow inbound http(s) traffic, install epel release, node v8.x, various dependencies, restart server when necessary, replace nginx configuration file with reverse proxy config, and run the needed yarn commands.

## Related Issue

https://github.com/CodeForNC/reentry-resources-hub/issues/45

## Motivation and Context

Looking to automate the deployment in AWS environments as quickly as possible. It's a simple an succinct script that should be easily modified in the future, as needed.
## How Has This Been Tested?

Script was executed numerous line by line during initial writing using a newly installed CentOS 7 minimal image. Additionally, scripts were run in totality on same CentOS 7 machine after clearing all previous package installations and repos. In all tests, browsing was possible to http://Ip_Addr:80 of the host server, which successfully proxied to port 3001 (can add 3000 as additional location in nginx config if needed). 

## Checklist:

- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Comment by ejaxon** [comment]
Thanks, @giancarlopetrini! I'll review in the next few days and integrate.

**Comment by giancarlopetrini** [comment]
No problem @ejaxon - hope it's helpful! Feel free to critique and request changes.

**Comment by ejaxon** [comment]
Hey @giancarlopetrini, this PR is set to merge into the 'deployement' branch of the main repo. I think I screwed you up on that one - that was a branch I started for this 3 months ago, but should have deleted. 

Could you redo this PR to merge into the master branch?

**Comment by giancarlopetrini** [comment]
Yup!

**Pull request closed without merging**
