### PR TITLE
Generate static site

### PR DESCRIPTION
**Pull request by brendanyounger**
This repo generates a completely static site for easy deployment.

## Description

I simplified much of the front end code as well as removed most of the server-side code since the react-snapshot package takes care of generating the complete static site without needing server-side rendering.

There are some minor tweaks needed to point the content submodule back to the CodeForNC version and to the CodeForNC github pages site or other static site.  Let me know if you want help with any of this.

### CODE REVIEW

**Comment by marshallj** [comment]
Hi Brendan,

Thanks for the PR. I pulled it down last night and got it running. It looks great, and this approach definitely simplifies the project quite a bit, which is a good thing. 

The original approach with the server side rendering was to optimize for SEO so the site would be easier to find for folks that desperately need access to the reentry information. We felt this was an important feature of the development. @ejaxon and I are not up to speed with react-snapshot, but it appears that the [docs](https://www.npmjs.com/package/react-snapshot) indicate it accounts for at lease some SEO features. 

This is the section in the docs  I am referring to: 

>The snapshots still have the normal JS bundle included, so once that downloads the site will function exactly as before (i.e. instantaneous page transitions), but you serve real, functional HTML & CSS as soon as possible. It's good for SEO (yes Google crawls SPAs now but they still reward perf and this perfs like a banshee), it's good if your JS is broken or something render-blocking has a network fail, it's good for accessibility, it's good for Slackbot or Facebook to read your opengraph tags, it's just good.

Can you speak to the SEO capabilities of your approach, before we pull this in? We are specifically wondering about the ability of all search engines to 'see' the content on the page for SEO. With this approach, are the search engines able to handle rendering that is dependent on an asynchronous API call? And do you have any additional recommendations to enhance SEO on the site?

Thanks,
Jason

**Comment by ejaxon** [comment]
Just to add a bit of clarification to Jason's question, we're thinking of changing the back end to use the same GraphQL API that the admin site will use. The straightforward way to implement that is simply to use a GraphQL client in the front-end code and let it handle the API request and pass the result in through component props.

The question then is whether that messes up the use of react-snapshot since the initial state of the site being snapshotted would probably not include any of the content. 

An alternative method would be to have the server call the API. Probably doable, but non-standard.

**Comment by brendanyounger** [comment]
The current version auto-generates a completely static site as seen here: https://brendanyounger.github.io/reentry-resources-hub/.  That's as good as it gets for SEO optimization.

Eric, you can look at the code in `src/components/App.jsx`.  That's the only call to the backend database which you can replace by a call to the GraphQL api if you want.  React snapshot is smart enough to pull the data from whatever backend you want when generating the static HTML.

**Comment by ejaxon** [comment]
Not sure why I didn't see the instructions [here](https://www.npmjs.com/package/react-snapshot#dynamic-data) before on how to deal with data being fetched asynchronously. So, yes, no problem there - we'll just be switching the API (and it won't be served any longer from server.js in this project). 

My only question at this point is stability/long-term support. But it doesn't look like backing out and taking a different approach in the future would be a particularly big deal and it certainly simplifies things, so I'm for it.

**Comment by marshallj** [comment]
**ALL CONTRIBUTORS:** To simplify the code base, and for long term sustainability @ejaxon and I have decided to move forward with merging this PR. Take note that this PR changes the code base significantly, and you should pull it into any dev branch you are currently working on ASAP. Please let me know if you have any questions.

**Comment by Sadaajit** [comment]
I’m sorry, but I don’t understand what this means. I don’t know what PR is. Too much a newbie I guess.

**Pull request merged**
