### PR TITLE
Added copy for Housing intro

### PR DESCRIPTION
**Pull request by sparklebunny**
General copy for Housing Resources page that includes links to FTC
website for credit report and the National Resource Reentry Center
housing resources page.

### CODE REVIEW

**Comment by ejaxon** [comment]
@sparklebunny I ended up restoring some of the original language from the Buncombe site, mostly to simplify language. Also, thinking about the fact that we have two audiences, the person with the criminal record and possibly a person at an agency trying to help, that original language both kept things simple and alerted the helping person to the key requirements. 

Also fixed a minor typo in the list.

Hope that's ok.

**Comment by sparklebunny** [comment]
Oh no - not a typo! I'll write the next copy with both parties more in
mind. I'm ready to commit the next set of text. With the new changes to the
repo, do you want me to change the commit process to the "Render a topic
page" directions? Thanks!

**Comment by ejaxon** [comment]
@sparklebunny - I've created a new issue here: https://github.com/CodeForNC/reentry-resources-hub/issues/37. We've also got a full example built for health (national/state + buncombe county, both content and resources) that is referred to there.

**Comment by ejaxon** [comment]
Probably should have created separate tasks for each section, but no time this AM.

**Pull request merged**
