### PR TITLE
Updated Intro Text For Benefits

### PR DESCRIPTION
**Pull request by ChoznJuan**
added the intro text for the "Public Benefits" tab under guilford county
## Description

added the text for the Public Benefits tab for guildford county.  i updated the link for the guilford county dept of health and human services

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ejaxon** [comment]
@ChoznJuan You should assume that any general/national/state information will be included above this text on the page from the common content So the first 2 paragraphs of this shouldn't really be part of this one, only the last, which is Guilford-specific.

**Comment by ejaxon** [comment]
You might want to collaborate with @sparklebunny on this - I think she is doing the common public benefits section right now.

**Comment by ChoznJuan** [comment]
Okay. I'll reach out to @sparklebunny. Thanks

**Comment by ejaxon** [comment]
Just doing some cleanup and closing this now.

**Pull request closed without merging**
